pipeline:
  build:
    image: circleci/php:7.1-browsers
    volumes:
      - /tmp/composer-cache:/root/.composer/cache/
    commands:
      - sudo cp .env.dusk .env
      - sudo composer install --ignore-platform-reqs
      - sudo php artisan key:generate
      - sudo touch database/database.sqlite
      - sudo ./vendor/bin/phpunit
      - sudo php artisan serve &
      - sudo php artisan dusk
